# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_pw', models.CharField(max_length=20)),
                ('customer_mail', models.CharField(max_length=100)),
                ('customer_total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Earthquakes',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_name', models.CharField(max_length=50)),
                ('eq_region', models.CharField(max_length=30)),
                ('fund_total_amount', models.IntegerField(blank=True, null=True)),
                ('fund_people_num', models.IntegerField(blank=True, null=True)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'earthquakes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_amount', models.IntegerField()),
                ('fund_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_name', models.CharField(max_length=100)),
                ('reward_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'reward',
                'managed': False,
            },
        ),
    ]
